# Generated by Django 5.2.8 on 2025-11-20 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment_Mode",
            fields=[
                ("mode_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("app_key", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_entity",
                    models.ForeignKey(
                        help_text="The underlying account (e.g., Bank Account) for this payment mode.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_payment_modes",
                        to="entities.entity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_modes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Mode",
                "verbose_name_plural": "Payment Modes",
            },
        ),
    ]
