# Generated by Django 5.2.8 on 2025-12-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_modes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Internal key e.g., 'phonepe'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("supports_wallet", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="URL or path to icon",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
