# Generated by Django 5.2.8 on 2025-12-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_modes", "0002_supportedapp"),
    ]

from payment_modes.constants import SUPPORTED_APPS

def populate_supported_apps(apps, schema_editor):
    SupportedApp = apps.get_model("payment_modes", "SupportedApp")
    for app_data in SUPPORTED_APPS:
        SupportedApp.objects.create(
            key=app_data["key"],
            name=app_data["name"],
            supports_wallet=app_data["supports_wallet"],
            icon=app_data["icon"]
        )

def reverse_populate(apps, schema_editor):
    SupportedApp = apps.get_model("payment_modes", "SupportedApp")
    SupportedApp.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("payment_modes", "0002_supportedapp"),
    ]

    operations = [
        migrations.RunPython(populate_supported_apps, reverse_populate),
    ]
