# Generated by Django 5.2.8 on 2025-12-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_alter_entity_type"),
        ("payment_modes", "0003_populate_supported_apps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment_mode",
            name="linked_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="The underlying account (e.g., Bank Account) for this payment mode.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_payment_modes",
                to="entities.entity",
            ),
        ),
    ]
