# Generated by Django 5.2.8 on 2025-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT", "Account"),
                    ("EXTERNAL_PAYEE", "External Payee"),
                    ("CATEGORY", "Category"),
                    ("WALLET", "Digital Wallet"),
                    ("SYSTEM", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
