# Generated by Django 5.2.8 on 2025-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_alter_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
