# Generated by Django 5.2.8 on 2025-12-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0003_entity_current_balance"),
        ("payment_modes", "0004_alter_payment_mode_linked_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional category for classification",
                        limit_choices_to={"type": "CATEGORY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_transactions",
                        to="entities.entity",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment mode used (e.g., UPI, Cash)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment_modes.payment_mode",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        help_text="The entity receiving the money (Destination)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transactions",
                        to="entities.entity",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        help_text="The entity sending the money (Source)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transactions",
                        to="entities.entity",
                    ),
                ),
            ],
        ),
    ]
